-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-12 21:39:24 AEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g
-- Student Name: Namrata Palai
-- Student ID: 31002188

set echo on
spool mau_schema_output.txt

DROP TABLE artist CASCADE CONSTRAINTS;

DROP TABLE artwork CASCADE CONSTRAINTS;

DROP TABLE artwork_status CASCADE CONSTRAINTS;

DROP TABLE artwork_style CASCADE CONSTRAINTS;

DROP TABLE customer CASCADE CONSTRAINTS;

DROP TABLE exhibition CASCADE CONSTRAINTS;

DROP TABLE gallery CASCADE CONSTRAINTS;

DROP TABLE sale CASCADE CONSTRAINTS;

CREATE TABLE artist (
    artist_code       NUMBER(7) NOT NULL,
    artist_title      VARCHAR2(10 CHAR) NOT NULL,
    artist_fname      VARCHAR2(30 CHAR),
    artist_lname      VARCHAR2(30 CHAR),
    artist_street     VARCHAR2(30 CHAR) NOT NULL,
    artist_town       VARCHAR2(10 CHAR) NOT NULL,
    artist_state      VARCHAR2(10 CHAR) NOT NULL,
    artist_phone_no   NUMBER(10),
    artwork_stock     NUMBER(3) NOT NULL
);

COMMENT ON COLUMN artist.artist_code IS
    'artist number';

COMMENT ON COLUMN artist.artist_title IS
    'artist title';

COMMENT ON COLUMN artist.artist_fname IS
    'artist first name';

COMMENT ON COLUMN artist.artist_lname IS
    'artist last name';

COMMENT ON COLUMN artist.artist_street IS
    'artist address: street';

COMMENT ON COLUMN artist.artist_town IS
    'artist address: city';

COMMENT ON COLUMN artist.artist_state IS
    'artist address: state';

COMMENT ON COLUMN artist.artist_phone_no IS
    'artist contact number';

COMMENT ON COLUMN artist.artwork_stock IS
    'artist artwork current stock';

ALTER TABLE artist ADD CONSTRAINT artist_pk PRIMARY KEY ( artist_code );

CREATE TABLE artwork (
    artwork_no            NUMBER(7) NOT NULL,
    artist_code           NUMBER(7) NOT NULL,
    artwork_title         VARCHAR2(10 CHAR) NOT NULL,
    artwork_accept_date   DATE NOT NULL,
    artwork_mrp           NUMBER(7, 2) NOT NULL,
    art_media_desc        VARCHAR2(50 CHAR) NOT NULL,
    artwork_style         VARCHAR2(50 CHAR) NOT NULL
);

COMMENT ON COLUMN artwork.artwork_no IS
    'artwork number';

COMMENT ON COLUMN artwork.artist_code IS
    'artist number';

COMMENT ON COLUMN artwork.artwork_title IS
    'artwork title';

COMMENT ON COLUMN artwork.artwork_accept_date IS
    'artwork accept date';

COMMENT ON COLUMN artwork.artwork_mrp IS
    'artwork maximum retail price';

COMMENT ON COLUMN artwork.art_media_desc IS
    'Artwork media description';

COMMENT ON COLUMN artwork.artwork_style IS
    'artwork style';

ALTER TABLE artwork ADD CONSTRAINT artwork_pk PRIMARY KEY ( artwork_no,
                                                            artist_code );

CREATE TABLE artwork_status (
    status_id        NUMBER(7) NOT NULL,
    update_date      DATE NOT NULL,
    artwork_status   VARCHAR2(50 CHAR) NOT NULL,
    artwork_no       NUMBER(7) NOT NULL,
    artist_code      NUMBER(7) NOT NULL,
    gallery_id       NUMBER(7)
);

ALTER TABLE artwork_status
    ADD CONSTRAINT check_status CHECK ( artwork_status IN (
        'In MAU Warehouse',
        'On display by a gallery',
        'Returned to Painter',
        'Sold',
        'in Transit'
    ) );

COMMENT ON COLUMN artwork_status.status_id IS
    'surrogate key: status id';

COMMENT ON COLUMN artwork_status.update_date IS
    'artwork status upadte date';

COMMENT ON COLUMN artwork_status.artwork_status IS
    'artwork_status';

COMMENT ON COLUMN artwork_status.artwork_no IS
    'artwork number';

COMMENT ON COLUMN artwork_status.artist_code IS
    'artist number';

COMMENT ON COLUMN artwork_status.gallery_id IS
    'Gallery ID';

CREATE UNIQUE INDEX artwork_status__idx ON
    artwork_status (
        gallery_id
    ASC );

ALTER TABLE artwork_status ADD CONSTRAINT artwork_status_pk PRIMARY KEY ( status_id
);

ALTER TABLE artwork_status
    ADD CONSTRAINT artworkstatus_uq UNIQUE ( artwork_no,
                                             artist_code,
                                             update_date );

CREATE TABLE artwork_style (
    artwork_style    VARCHAR2(50 CHAR) NOT NULL,
    artwork_style1   VARCHAR2(50 CHAR)
);

COMMENT ON COLUMN artwork_style.artwork_style IS
    'artwork style';

COMMENT ON COLUMN artwork_style.artwork_style1 IS
    'artwork style';

ALTER TABLE artwork_style ADD CONSTRAINT artwork_style_pk PRIMARY KEY ( artwork_style
);

CREATE TABLE customer (
    customer_id          NUMBER(7) NOT NULL,
    customer_title       VARCHAR2(10 CHAR) NOT NULL,
    customer_fname       VARCHAR2(30 CHAR),
    customer_lname       VARCHAR2(30 CHAR),
    customer_street      VARCHAR2(20 CHAR) NOT NULL,
    customer_town        VARCHAR2(20 CHAR) NOT NULL,
    customer_state       VARCHAR2(10 CHAR) NOT NULL,
    customer_phone       NUMBER(10) NOT NULL,
    cust_business_name   VARCHAR2(50 CHAR)
);

COMMENT ON COLUMN customer.customer_id IS
    'Customer ID';

COMMENT ON COLUMN customer.customer_title IS
    'Customer Title';

COMMENT ON COLUMN customer.customer_fname IS
    'Customer first Name';

COMMENT ON COLUMN customer.customer_lname IS
    'Customer Last name';

COMMENT ON COLUMN customer.customer_street IS
    'Customer address: street';

COMMENT ON COLUMN customer.customer_town IS
    'customer address: town';

COMMENT ON COLUMN customer.customer_state IS
    'customer address: state';

COMMENT ON COLUMN customer.customer_phone IS
    'custome phone number';

COMMENT ON COLUMN customer.cust_business_name IS
    'customer business name';

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( customer_id );

CREATE TABLE exhibition (
    exhibition_id           NUMBER(7) NOT NULL,
    exhibition_start_date   DATE NOT NULL,
    exhibition_end_date     DATE NOT NULL,
    feature                 VARCHAR2(10 CHAR) NOT NULL,
    artwork_no              NUMBER(7) NOT NULL,
    artist_code             NUMBER(7) NOT NULL,
    gallery_id              NUMBER(7) NOT NULL
);

ALTER TABLE exhibition
    ADD CONSTRAINT check_feature CHECK ( feature IN (
        'No',
        'Yes'
    ) );

COMMENT ON COLUMN exhibition.exhibition_id IS
    'surrogte key: exhibition id';

COMMENT ON COLUMN exhibition.exhibition_start_date IS
    'exhibition start date';

COMMENT ON COLUMN exhibition.exhibition_end_date IS
    'exhibition end date';

COMMENT ON COLUMN exhibition.feature IS
    'feature in catalogue';

COMMENT ON COLUMN exhibition.artwork_no IS
    'artwork number';

COMMENT ON COLUMN exhibition.artist_code IS
    'artist number';

COMMENT ON COLUMN exhibition.gallery_id IS
    'Gallery ID';

ALTER TABLE exhibition ADD CONSTRAINT exhibition_pk PRIMARY KEY ( exhibition_id )
;

ALTER TABLE exhibition
    ADD CONSTRAINT exhibition_start_date UNIQUE ( exhibition_start_date,
                                                  artwork_no,
                                                  artist_code );

CREATE TABLE gallery (
    gallery_id             NUMBER(7) NOT NULL,
    gallery_name           VARCHAR2(30 CHAR) NOT NULL,
    gallery_manager_name   VARCHAR2(50 CHAR) NOT NULL,
    gallery_street         VARCHAR2(30 CHAR) NOT NULL,
    gallery_town           VARCHAR2(20 CHAR) NOT NULL,
    gallery_state          VARCHAR2(30 CHAR) NOT NULL,
    gallery_contact_no     NUMBER(10) NOT NULL,
    gallery_commission     NUMBER(10, 2) NOT NULL,
    gallery_opens          VARCHAR2(30 CHAR) NOT NULL,
    gallery_closes         VARCHAR2(30 CHAR) NOT NULL
);

COMMENT ON COLUMN gallery.gallery_id IS
    'Gallery ID';

COMMENT ON COLUMN gallery.gallery_name IS
    'Gallery Name';

COMMENT ON COLUMN gallery.gallery_manager_name IS
    'Gallery Manager Name';

COMMENT ON COLUMN gallery.gallery_street IS
    'Gallery addres: street';

COMMENT ON COLUMN gallery.gallery_town IS
    'Gallery address: town';

COMMENT ON COLUMN gallery.gallery_state IS
    'Gallery address: state';

COMMENT ON COLUMN gallery.gallery_contact_no IS
    'Gallery Contact Number';

COMMENT ON COLUMN gallery.gallery_commission IS
    'Gallery Commission';

COMMENT ON COLUMN gallery.gallery_opens IS
    'Gallery Open time';

COMMENT ON COLUMN gallery.gallery_closes IS
    'Gallery Close time';

ALTER TABLE gallery ADD CONSTRAINT gallery_pk PRIMARY KEY ( gallery_id );

CREATE TABLE sale (
    sale_id         NUMBER(7) NOT NULL,
    date_of_sale    DATE NOT NULL,
    sale_price      NUMBER(7, 2) NOT NULL,
    customer_id     NUMBER(7) NOT NULL,
    exhibition_id   NUMBER(7) NOT NULL
);

COMMENT ON COLUMN sale.sale_id IS
    'sale id';

COMMENT ON COLUMN sale.date_of_sale IS
    'date of sale';

COMMENT ON COLUMN sale.sale_price IS
    'sale price';

COMMENT ON COLUMN sale.customer_id IS
    'Customer ID';

COMMENT ON COLUMN sale.exhibition_id IS
    'surrogte key: exhibition id';

CREATE UNIQUE INDEX sale__idx ON
    sale (
        exhibition_id
    ASC );

ALTER TABLE sale ADD CONSTRAINT sale_pk PRIMARY KEY ( sale_id );

ALTER TABLE artwork
    ADD CONSTRAINT artist_to_artwork FOREIGN KEY ( artist_code )
        REFERENCES artist ( artist_code );

ALTER TABLE artwork
    ADD CONSTRAINT artwork_style_to_artwork FOREIGN KEY ( artwork_style )
        REFERENCES artwork_style ( artwork_style );

ALTER TABLE artwork_style
    ADD CONSTRAINT artwork_style_to_artwork_style FOREIGN KEY ( artwork_style1 )
        REFERENCES artwork_style ( artwork_style );

ALTER TABLE artwork_status
    ADD CONSTRAINT artwork_to_artwork_status FOREIGN KEY ( artwork_no,
                                                           artist_code )
        REFERENCES artwork ( artwork_no,
                             artist_code );

ALTER TABLE exhibition
    ADD CONSTRAINT artwork_to_exhibition FOREIGN KEY ( artwork_no,
                                                       artist_code )
        REFERENCES artwork ( artwork_no,
                             artist_code );

ALTER TABLE sale
    ADD CONSTRAINT customer_to_sale FOREIGN KEY ( customer_id )
        REFERENCES customer ( customer_id );

ALTER TABLE sale
    ADD CONSTRAINT exhibition_to_sale FOREIGN KEY ( exhibition_id )
        REFERENCES exhibition ( exhibition_id );

ALTER TABLE artwork_status
    ADD CONSTRAINT gallery_to_artwork_status FOREIGN KEY ( gallery_id )
        REFERENCES gallery ( gallery_id );

ALTER TABLE exhibition
    ADD CONSTRAINT gallery_to_exhibition FOREIGN KEY ( gallery_id )
        REFERENCES gallery ( gallery_id );

spool off
set echo off

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             2
-- ALTER TABLE                             21
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
